[package]
name = "eaesy-rtfm"
version = "0.1.0"
authors = ["Tmplt <tmplt@dragons.rocks>"]
edition = "2018"

[dependencies]
cortex-m-rt = "0.6.7"
s32k144 = "0.10.0"
s32k144evb = "0.7.0"

[patch.crates-io]
s32k144evb = { git = "https://github.com/tmplt/s32k144evb.rs.git" }

